name: 🐛 Bug Report
description: Create a report to help us improve Synapse Hub
title: '[BUG] '
labels: ['bug', 'needs-triage']
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug you encountered
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - Backend (FastAPI/Python)
        - Frontend (SvelteKit)
        - Cursor Connector
        - Health Monitoring
        - Documentation
        - CI/CD Pipeline
        - Other
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe what should have happened
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe what actually happened
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots/Logs
      description: If applicable, add screenshots or log output
      placeholder: Paste screenshots or log output here

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: What platform are you using?
      options:
        - Windows
        - macOS
        - Linux (Ubuntu)
        - Linux (other)
        - Raspberry Pi
        - Other
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python Version
      description: What version of Python are you using? (if applicable)
      placeholder: '3.11.5'

  - type: input
    id: node-version
    attributes:
      label: Node.js Version
      description: What version of Node.js are you using? (if applicable)
      placeholder: '20.10.0'

  - type: textarea
    id: environment
    attributes:
      label: Environment Details
      description: Any additional environment details
      placeholder: |
        - Cursor IDE version:
        - Browser version:
        - Backend health status:
        - Any relevant configuration:

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please check all applicable boxes
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have tried the health verification script (`python scripts/verify_health.py`)
        - label: I have checked the documentation
        - label: I can reproduce this issue consistently

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information that might be helpful
